name: Hanolcare Crawler Automation

on:
  workflow_dispatch:  # 수동 실행 가능

jobs:
  crawl-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: 레포지토리 코드 체크아웃
      uses: actions/checkout@v4

    - name: Python 환경 설정
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: 의존성 설치하기
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install chromium
    
    - name: 크롤링 실행하기
      env:
        GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
      run: |
        python src/crawler.py --auto 
